from enum import StrEnum


class WorkOrderType(StrEnum):
    OSC = "OSC"
    OSCP = "OSCP"
    OSM = "OSM"
    OSP = "OSP"
    CHECKLIST = "CHECKLIST"


class WorkOrderStatus(StrEnum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    SUSPENDED = "SUSPENDED"
    EXECUTION_DONE = "EXECUTION_DONE"
    CLOSED = "CLOSED"


class EventType(StrEnum):
    CREATED = "CREATED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    EXECUTION_SUSPENDED = "EXECUTION_SUSPENDED"
    EXECUTION_RESUMED = "EXECUTION_RESUMED"
    EXECUTION_FINISHED = "EXECUTION_FINISHED"
    CLOSED = "CLOSED"
    REVIEW_CREATED = "REVIEW_CREATED"
    OSCP_REPROGRAMMED = "OSCP_REPROGRAMMED"
    WINDOW_NONCONFORMITY = "WINDOW_NONCONFORMITY"


class RoleCode(StrEnum):
    ADMIN = "ADMIN"
    COORDINATOR = "COORDINATOR"
    PLANNER = "PLANNER"
    TECHNICIAN = "TECHNICIAN"
    REQUESTER = "REQUESTER"
    ADMINISTRATIVE = "ADMINISTRATIVE"